name: Elm-Webpage

on:
  push:
    branches: [main]
    
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - name: Setup Elm environment
      uses: ./.github/workflows/action.yml
      with: 
        elm-version: 0.19.1
    - name: Compile elm Main file
      run: elm make src/Main.elm
     
    

    
